name: "build-release-ubuntu"
on:
  push:
  release:
    types: [published]
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: master
jobs:
  build:
    name: Ubuntu release build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          path: liblandstalker
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: |
             sudo apt-get update
             sudo apt-get install -y \
                gcc-11 \
                g++-11 \
                cmake

      - name: 'Build Static Release'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake -S . -B build -DLANDSTALKER_BUILD_SHARED=OFF -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j32
          cmake --install build --prefix ./lib

      - name: 'Build Static Debug'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake -S . -B build_debug -DLANDSTALKER_BUILD_SHARED=OFF -DCMAKE_BUILD_TYPE=Debug
          cmake --build build_debug -j32
          cmake --install build_debug --prefix ./lib_debug

      - name: 'Build Shared Release'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake -S . -B build_shared -DLANDSTALKER_BUILD_SHARED=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build_shared -j32
          cmake --install build_shared --prefix ./lib

      - name: 'Build Shared Debug'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake -S . -B build_shared_debug -DLANDSTALKER_BUILD_SHARED=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build build_shared_debug -j32
          cmake --install build_shared_debug --prefix ./lib_debug

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: liblandstalker_binary_ubuntu
          path: |
            ${{github.workspace}}/liblandstalker/lib
            ${{github.workspace}}/liblandstalker/lib_debug
