name: "build-release-windows"
on:
  push:
  release:
    types: [published]
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: master
jobs:
  build:
    name: Windows release build
    runs-on: windows-2022
    env:
      BUILD_TYPE: Release
    strategy:
      fail-fast: false
    steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'

      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          path: liblandstalker
          submodules: 'recursive'

      - name: 'Build Static Release'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake -S . -B build -DLANDSTALKER_BUILD_SHARED=OFF
          cmake --build build --config Release -j32
          cmake --install build --prefix ./lib --config Release

      - name: 'Build Static Debug'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake --build build --config Debug -j32
          cmake --install build --prefix ./lib_debug --config Debug

      - name: 'Build DLL Release'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake -S . -B build_dll -DLANDSTALKER_BUILD_SHARED=ON
          cmake --build build_dll --config Release -j32
          cmake --install build_dll --prefix ./dll --config Release

      - name: 'Build DLL Debug'
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          cmake --build build_dll --config Debug -j32
          cmake --install build_dll --prefix ./dll_debug --config Debug

      - name: Compress artifacts
        working-directory: ${{github.workspace}}/liblandstalker
        run: |
          Compress-Archive -Path dll/*,dll_debug/*,lib/*,lib_debug/* -Destination liblandstalker.zip

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: landstalker_binary_windows
          path: ${{github.workspace}}/liblandstalker/build/Release/liblandstalker.zip
